// ======================================
// Cover Page (V2 Stable)
// ======================================

export const coverPage = (

  doc,

  {

    logo,

    userName,

    portfolioScore,

    reportPeriod

  }

) => {

  const PAGE_WIDTH = 210;
  const CENTER = PAGE_WIDTH / 2;

  const today = new Date().toLocaleDateString("en-IN");

  const centerText = (

    text,

    y,

    size = 12

  ) => {

    doc.setFontSize(size);

    const width = doc.getTextWidth(text);

    doc.text(

      text,

      CENTER - width / 2,

      y

    );

  };

  // =====================================
  // Background
  // =====================================

  doc.setFillColor(

    15,

    23,

    42

  );

  doc.rect(

    0,

    0,

    210,

    297,

    "F"

  );

  // =====================================
  // Logo
  // =====================================

  if (logo) {

    doc.addImage(

      logo,

      "PNG",

      80,

      20,

      50,

      50

    );

  }

  // =====================================
  // Title
  // =====================================

  doc.setTextColor(

    255,

    255,

    255

  );

  centerText(

    "MF Portfolio",

    88,

    28

  );

  centerText(

    "Performance Report",

    102,

    24

  );

  // =====================================
  // Subtitle
  // =====================================

  doc.setTextColor(

    190,

    190,

    190

  );

  centerText(

    "Professional Mutual Fund Analytics",

    116,

    13

  );

  // =====================================
  // Badge
  // =====================================

  let badge = "Bronze";

  let badgeColor = [

    180,

    83,

    9

  ];

  if (

    portfolioScore >= 90

  ) {

    badge = "Diamond";

    badgeColor = [

      6,

      182,

      212

    ];

  }

  else if (

    portfolioScore >= 80

  ) {

    badge = "Gold";

    badgeColor = [

      234,

      179,

      8

    ];

  }

  else if (

    portfolioScore >= 70

  ) {

    badge = "Silver";

    badgeColor = [

      156,

      163,

      175

    ];

  }

  doc.setFillColor(

    ...badgeColor

  );

  doc.roundedRect(

    60,

    136,

    90,

    18,

    5,

    5,

    "F"

  );

  doc.setTextColor(

    0,

    0,

    0

  );

  centerText(

    `${badge} Portfolio`,

    148,

    14

  );

  // =====================================
  // Portfolio Details
  // =====================================

  doc.setTextColor(

    255,

    255,

    255

  );

  centerText(

    `Prepared For : ${userName}`,

    182,

    13

  );

  centerText(

    `Generated On : ${today}`,

    194,

    13

  );

  centerText(

    `Report Period : ${reportPeriod}`,

    206,

    13

  );

  // =====================================
  // Footer
  // =====================================

  doc.setDrawColor(

    70,

    70,

    70

  );

  doc.line(

    25,

    270,

    185,

    270

  );

  doc.setTextColor(

    170,

    170,

    170

  );

  centerText(

    "Generated by MF Portfolio Manager",

    279,

    10

  );

  centerText(

    "Version 2.0",

    286,

    9

  );

  doc.addPage();

};