// ======================================
// Cover Page
// ======================================

export const coverPage = (

  doc,

  {

    logo,

    userName,

    portfolioScore,

    reportPeriod

  }


) => {

  const today =
    new Date().toLocaleDateString(
      "en-IN"
    );

  // =====================================
  // Background
  // =====================================

  doc.setFillColor(

    15,

    23,

    42

  );

  doc.rect(

    0,

    0,

    210,

    297,

    "F"

  );

  // =====================================
  // Logo Circle
  // =====================================

  doc.setFillColor(

    37,

    99,

    235

  );

if (logo) {

  doc.addImage(

    logo,

    "PNG",

    82,

    28,

    45,

    45

  );

}

  doc.setTextColor(

    255,

    255,

    255

  );

  doc.setFontSize(

    22

  );

  doc.text(

    "MF",

    98,

    60

  );

  // =====================================
  // Title
  // =====================================

  doc.setFontSize(

    30

  );

  doc.text(

    "MF Portfolio",

    60,

    95

  );

  doc.text(

    "Performance Report",

    36,

    110

  );

  // =====================================
  // Subtitle
  // =====================================

  doc.setFontSize(

    14

  );

  doc.setTextColor(

    180,

    180,

    180

  );

  doc.text(

    "Professional Mutual Fund Analytics",

    40,

    125

  );

  // =====================================
  // Rating Badge
  // =====================================

  let badge = "Bronze";

  let color = [

    180,

    83,

    9

  ];

  if (

    portfolioScore >= 90

  ) {

    badge = "Gold";

    color = [

      234,

      179,

      8

    ];

  }

  else if (

    portfolioScore >= 75

  ) {

    badge = "Silver";

    color = [

      156,

      163,

      175

    ];

  }

  doc.setFillColor(

    ...color

  );

  doc.roundedRect(

    65,

    150,

    80,

    18,

    5,

    5,

    "F"

  );

  doc.setTextColor(

    0,

    0,

    0

  );

  doc.setFontSize(

    15

  );

  doc.text(

    `${badge} Portfolio`,

    82,

    162

  );

  // =====================================
  // Information
  // =====================================

  doc.setTextColor(

    255,

    255,

    255

  );

  doc.setFontSize(

    13

  );

  doc.text(

    `Prepared For : ${userName}`,

    20,

    205

  );

  doc.text(

    `Generated On : ${today}`,

    20,

    220

  );

  doc.text(

    `Report Period : ${reportPeriod}`,

    20,

    235

  );

  // =====================================
  // Footer
  // =====================================

  doc.setDrawColor(

    70,

    70,

    70

  );

  doc.line(

    15,

    270,

    195,

    270

  );

  doc.setTextColor(

    160,

    160,

    160

  );

  doc.setFontSize(

    10

  );

  doc.text(

    "Generated by MF Portfolio Manager",

    15,

    280

  );

  doc.text(

    "Version 2.0",

    170,

    280

  );

  doc.addPage();

};