// ======================================
// Footer
// ======================================

export const footer = (doc) => {

  const totalPages =

    doc.getNumberOfPages();

  const generatedOn =

    new Date().toLocaleString(

      "en-IN",

      {

        dateStyle: "medium",

        timeStyle: "short"

      }

    );

  // ======================================
  // Add Footer To Every Page
  // ======================================

  for (

    let page = 1;

    page <= totalPages;

    page++

  ) {

    doc.setPage(

      page

    );

    // Separator Line

    doc.setDrawColor(

      210,

      210,

      210

    );

    doc.line(

      14,

      288,

      196,

      288

    );

    // Left

    doc.setFontSize(

      8

    );

    doc.setTextColor(

      120,

      120,

      120

    );

    doc.text(

      "Generated by MF Portfolio Manager",

      14,

      293

    );

    // Center

    doc.text(

      generatedOn,

      82,

      293

    );

    // Right

    doc.text(

      `Page ${page} of ${totalPages}`,

      170,

      293

    );

  }

};